name: Create Superuser

on:
  workflow_dispatch:

jobs:
  createsuperuser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Create superuser
      run: |
        echo "from django.contrib.auth import get_user_model; \
              User = get_user_model(); \
              User.objects.create_superuser('mazen', 'mazin72020@email.com', 'MAZINA12@')" \
              | python manage.py shell
